/*
------------------------------------------------------------------------------------
Settings for: ATOPizzaFactory.ToolKit (Library/Toolkit)
Description:
    This Gradle settings file defines the structure of the ATOPizzaFactory Toolkit
    as a multi-module project.

    For more information on multi-project builds, see:
    https://docs.gradle.org/8.7/userguide/multi_project_builds.html
------------------------------------------------------------------------------------
*/

rootProject.name = 'ATOPizzaFactory.ToolKit'

include('core')
