/*
------------------------------------------------------------------------------------
Module: utils
Description:
    The purpose of this module is to provide basic utility classes and patterns
    for handling "core" objects, as well as the most fundamental terms and helpers
    possible in Java. It applies the 'java-library' plugin for API/implementation
    separation. JUnit Jupiter is included for unit testing.
------------------------------------------------------------------------------------
*/

plugins {
    id 'java-library'
}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
        }
    }
    test {
        java {
            srcDirs = ['src/test/java']
        }
    }
}

dependencies {
    // Internal dependencies
    // implementation project(':core')

    // External dependencies
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

test {
    useJUnitPlatform()
}
